name: Publish Service Test Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-versions: '1.17'
      - name: Run Test Coverage
        id: qa-stats
        run: |
          COVERAGE=$(go test -cover | sed '/coverage/!d' | sed 's/coverage: \([0-9]\+\.[0-9]\)%.*/\1/')
          echo "::set-output name=coverage::$COVERAGE"
      - name: Report Coverage
        uses: fjogeleit/http-request-action@master
        with:
          url: 'http://ec2-3-143-229-194.us-east-2.compute.amazonaws.com/'
          method: POST
          data: |
            {
              "event": "TrackTestCoverageEvent",
              "trigger": "${{ github.event_name }}",
              "Job_id": ${{ github.job}}
              "payload": {
                "service_name": "${{ github.repository }}",
                "coverage": "${{ step.qa-stats.outputs.coverage }"
              }
            }


